# Generated by Django 3.1 on 2020-09-08 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Practice', '0002_score_total'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='score',
            order_with_respect_to='added',
        ),
    ]
