# Generated by Django 3.1 on 2020-09-08 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Practice', '0003_auto_20200908_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['-added']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='score',
            order_with_respect_to=None,
        ),
    ]
