# Generated by Django 3.1 on 2020-09-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Practice', '0004_auto_20200908_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='percent',
            field=models.IntegerField(blank=True, default=40),
            preserve_default=False,
        ),
    ]
