# Generated by Django 3.1 on 2020-08-27 05:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Share', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
