# Generated by Django 3.1 on 2020-08-27 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Share', '0003_auto_20200827_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='uid',
        ),
    ]
