# Generated by Django 3.1 on 2020-08-27 06:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Share', '0004_remove_group_uid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Community',
        ),
    ]
