# Generated by Django 3.1 on 2020-09-11 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Share', '0007_auto_20200911_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='Share.community'),
            preserve_default=False,
        ),
    ]
